version: '3.7'

services:
  app:
    build:
      args:
        user: sofubi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lumen
    container_name: elon
    restart: unless-stopped
    working_dir: /var/www
    volumes:
     - ./:/var/www
    networks:
      - elon

  db:
    image: mysql:5.7
    container_name: elon_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - elon

  nginx:
    image: nginx:1.17-alpine
    container_name: elon_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - elon

networks:
  elon:
    driver: bridge
